import { Plan } from '@/types';

export const PLANS: Record<string, Plan> = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    priceAnnual: 0,
    analysesPerMonth: 1,
    urlsPerAnalysis: 5,
    llmCount: 1,
    competitorsShown: 3,
    historyDays: 7,
    features: {
      recommendations: false,
      exportPdf: false,
      exportMarkdown: false,
      api: false,
      whiteLabel: false,
    },
  },
  basic: {
    id: 'basic',
    name: 'Basic',
    price: 19,
    priceAnnual: 15,
    analysesPerMonth: 3,
    urlsPerAnalysis: 20,
    llmCount: 2,
    competitorsShown: 5,
    historyDays: 30,
    features: {
      recommendations: false,
      exportPdf: true,
      exportMarkdown: false,
      api: false,
      whiteLabel: false,
    },
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    price: 49,
    priceAnnual: 39,
    analysesPerMonth: 10,
    urlsPerAnalysis: 100,
    llmCount: 4,
    competitorsShown: 10,
    historyDays: 90,
    features: {
      recommendations: true,
      exportPdf: true,
      exportMarkdown: true,
      api: false,
      whiteLabel: false,
    },
  },
  business: {
    id: 'business',
    name: 'Business',
    price: 149,
    priceAnnual: 119,
    analysesPerMonth: -1,
    urlsPerAnalysis: 200,
    llmCount: 4,
    competitorsShown: -1,
    historyDays: 365,
    features: {
      recommendations: true,
      exportPdf: true,
      exportMarkdown: true,
      api: true,
      whiteLabel: true,
    },
  },
};
